export const SITE = {
  name: "Trenova",
  brand: "Trenova",
  legalName: "Trenova Retail Private Limited",
  tagline: "Trusted Quality. Affordable Style.",
  seoTitle:
    "Trenova | Premium Fashion & Activewear Online India",
  description:
    "Shop Trenova premium fashion, activewear & lifestyle essentials for men, women & kids. Trusted quality clothing at affordable prices. Shop India-wide now.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://shoptrenova.in",
  domain: "shoptrenova.in",
  locale: "en_IN",
  currency: "INR",
  currencySymbol: "₹",
  email: "NovaBrands.2026@gmail.com",
  phone: "+91 60062 16695",
  phoneSecondary: "+91 95966 56950",
  whatsapp: "916006216695",
  cin: "U47820JK2026PTC019539",
  instagramHandle: "@shoptrenova",
  ogImage: "/images/hero/cover-01.png",
  keywords: [
    "Trenova",
    "shop Trenova",
    "shoptrenova",
    "premium fashion brand",
    "premium fashion India",
    "activewear",
    "sportswear",
    "lifestyle essentials",
    "menswear",
    "womenswear",
    "kids fashion",
    "men clothing online",
    "women clothing online",
    "kids clothing online",
    "affordable luxury clothing",
    "trusted quality apparel",
    "online fashion store India",
    "buy clothes online India",
  ],
  address: {
    line1: "TI Arcade Complex, 1st Floor, Shop No. 1",
    line2: "Sangrama",
    city: "Sopore",
    state: "Jammu and Kashmir",
    postalCode: "193201",
    country: "India",
  },
  social: {
    instagram: "https://www.instagram.com/shoptrenova/",
    facebook: "https://facebook.com/shoptrenova",
    twitter: "https://x.com/shoptrenova",
    youtube: "https://youtube.com/@shoptrenova",
  },
} as const;

export const ANNOUNCEMENTS = [
  "Free shipping on orders above ₹999",
  "Premium Quality. Affordable Style. Trusted by You.",
  "Easy Returns | 7-Day Return Policy",
] as const;
